[package]
name = "coin_watch"
version = "0.1.0"
authors = ["600913 <600913@gmail.com>"]

[dependencies]
websocket = "0.20.2"
futures-await = "0.1.0"
tokio-core = "0.1.12"
termion = "1.5.1"
serde = "1.0.27"
serde_json = "1.0.9"
serde_derive = "1.0.27"
itertools = "0.7.6"
